merchant1 = Merchant.create!(name: 'Happy Lama')
shipment1 = merchant1.shipments.create!(name: 'Dancing Dora', address: '123 Main St.', state: 'NY', zip_code: 30187)
item1 = merchant1.items.create!(name: 'Flaming Red Hat', description: 'red lama hat', unit_price: 34.00)
item2 = merchant1.items.create!(name: 'Capybara Brown Coat', description: 'brown lama coat', unit_price: 31.55)
item3 = merchant1.items.create!(name: 'Orange Lama Shirt', description: 'orange lama shirt', unit_price: 37.00)
item4 = merchant1.items.create!(name: 'Banana Rama', description: 'banana rama hooper', unit_price: 12.33)

merchant2 = Merchant.create!(name: 'Sad Sloth')
shipment2 = merchant2.shipments.create!(name: 'Cyndee Valdez', address: '1099 Tax Lane.', state: 'DC', zip_code: 13799)
shipment3 = merchant2.shipments.create!(name: 'Juan Fernandez', address: '123 Main St.', state: 'NY', zip_code: 20187)
item5 = merchant2.items.create!(name: 'Mopey Monkey Chair', description: 'brown monkey Chair', unit_price: 12.00)
item6 = merchant2.items.create!(name: 'Leaping Lizzard Shirt', description: 'green lizzard shirt', unit_price: 22.45)
item7 = merchant2.items.create!(name: 'Dancing Octopus Shoes', description: 'purple octopus shoes', unit_price: 13.44)
item8 = merchant2.items.create!(name: 'Crazy Moth Rings', description: 'rainbow moth rings', unit_price: 15.77)
item9 = merchant2.items.create!(name: 'Cuddly Puppy Socks', description: 'blue puppy socks', unit_price: 12.10)
item10 = merchant2.items.create!(name: 'Krazy Kitten leggings', description: 'pink kitten leggings', unit_price: 19.99)

ShipmentItem.create!(shipment_id: shipment1.id, item_id: item1.id)
ShipmentItem.create!(shipment_id: shipment1.id, item_id: item2.id)
ShipmentItem.create!(shipment_id: shipment1.id, item_id: item3.id)
ShipmentItem.create!(shipment_id: shipment2.id, item_id: item5.id)
ShipmentItem.create!(shipment_id: shipment2.id, item_id: item6.id)
ShipmentItem.create!(shipment_id: shipment3.id, item_id: item6.id)
ShipmentItem.create!(shipment_id: shipment3.id, item_id: item7.id)
ShipmentItem.create!(shipment_id: shipment3.id, item_id: item8.id)
